# Generated by Django 4.1.2 on 2022-11-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='work_type',
        ),
    ]
