# Generated by Django 4.1.2 on 2022-11-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=255)),
                ('level_no', models.IntegerField(blank=True, null=True)),
                ('unit_no', models.IntegerField(blank=True, null=True)),
                ('lot_no', models.IntegerField(blank=True, null=True)),
                ('street_name', models.CharField(max_length=255)),
                ('street_type', models.CharField(max_length=255)),
                ('suffix', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=255)),
            ],
        ),
    ]
