# Generated by Django 4.1.2 on 2022-11-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytypes',
            old_name='unit_type',
            new_name='type_name',
        ),
    ]
