# Generated by Django 4.1.2 on 2022-11-23 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_businessdetails_property_is_business_property_lga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='business_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='company_ABN',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='business_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.businessdetails'),
        ),
    ]
