# Generated by Django 4.1.2 on 2022-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_streettypes_property_customer_property_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytypes',
            name='type_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
