# Generated by Django 4.1.2 on 2022-11-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_businessdetails_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='business_details',
        ),
        migrations.DeleteModel(
            name='BusinessDetails',
        ),
    ]
