# Generated by Django 4.1.2 on 2022-11-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertytypes_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_billing_address',
            field=models.BooleanField(default=False),
        ),
    ]
