# Generated by Django 4.1.2 on 2022-11-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_is_billing_address'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('is_billing_address', True)), fields=('customer',), name='unique_billing_address'),
        ),
    ]
