# Generated by Django 4.1.2 on 2022-10-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userroles_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
    ]
