# Generated by Django 4.1.2 on 2022-10-31 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companyupdaterequests_is_approved'),
        ('users', '0006_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companies'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('auditor', 'auditor'), ('field_worker', 'field_worker'), ('manager', 'manager'), ('customer', 'customer')], max_length=15),
        ),
    ]
