# Generated by Django 4.1.2 on 2022-11-15 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_staffassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StaffAssociation',
        ),
    ]
