# Generated by Django 4.1.2 on 2022-11-16 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companies_is_active'),
        ('users', '0011_staffassociate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffassociate',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companies'),
        ),
        migrations.AlterField(
            model_name='staffassociate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
