# Generated by Django 4.1.2 on 2022-11-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='ABN',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
