# Generated by Django 4.1.2 on 2022-11-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companyupdaterequests_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
