# Generated by Django 4.1.2 on 2022-11-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('residential', 'residential'), ('business', 'business')], max_length=30)),
                ('customer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_ABN', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_consent', models.CharField(choices=[('inferred', 'inferred'), ('expressed', 'expressed'), ('no', 'no')], max_length=30)),
                ('lead_status', models.CharField(choices=[('New Lead', 'New Lead'), ('Call Scheduled', 'Call Scheduled'), ('Contacted', 'Contacted'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost')], default='New Lead', max_length=50)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companies')),
            ],
        ),
    ]
