# Generated by Django 4.1.2 on 2022-11-02 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
    ]
