# Generated by Django 4.1.2 on 2022-11-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companies'),
        ),
    ]
