# Generated by Django 4.1.2 on 2022-11-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='created_on',
        ),
    ]
