# Generated by Django 4.1.2 on 2022-11-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customerinfo_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
