# Generated by Django 4.1.2 on 2022-11-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
        ('customer', '0005_customerinfo_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userroles'),
        ),
    ]
