# Generated by Django 4.1.2 on 2022-11-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customerinfo_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='lead_status',
            field=models.CharField(choices=[('New Lead', 'New Lead'), ('Contacted', 'Contacted'), ('Acquired', 'Acquired'), ('Lost', 'Lost')], default='New Lead', max_length=50),
        ),
    ]
