# Generated by Django 4.1.2 on 2022-11-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customerinfo_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='type',
        ),
    ]
