# Generated by Django 4.1.2 on 2022-11-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_customerinfo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='type',
            field=models.CharField(choices=[('residential', 'residential'), ('business', 'business')], default='New Lead', max_length=50),
        ),
    ]
